AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - "lib/generators/**/*.tt"

Style/FrozenStringLiteralComment:
  Enabled: true

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120
